fortune:
  build: fortune
  environment:
    FORTUNES: http://www.shlomifish.org/humour/fortunes/subversion

cookie:
  build: cookie
  links:
    - fortune
  ports:
    - "8000:8000"
  environment:
    FORTUNE: 'http://fortune:8000/fortune'
