fortune:
  build: fortune
  environment:
    FORTUNES: s3://nobel-mesos/fortune
    AWS_ACCESS_KEY_ID: AKIAJS4Z6ZPBUVPQTNEQ
    AWS_SECRET_ACCESS_KEY: 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

cookie:
  build: cookie
  links:
    - fortune
  ports:
    - "8000:8000"
  environment:
    FORTUNE: 'http://fortune:8000/fortune'
